### ISSUE TITLE
Slug tgz contains http-verbs test JAR

### ISSUE THREAD

**Issue by agilestevesmith** [hmrc/help-frontend#1]
New versions of help-frontend contain uk.gov.hmrc.http-verbs_2.11-1.5.0-tests.jar as a lib - can this please be removed

@hmrc/yta @xnejp03

**Comment by davesmith00000** [comment]
It looks like this was fixed at some point, do you concur @agilestevesmith?

**Comment by agilestevesmith** [comment]
Yes, http-verbs does not appear in search results
